// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/environmental_monitoring.proto
// Protobuf Java Version: 4.31.1

package ds.environmental;

@com.google.protobuf.Generated
public final class EnvironmentalMonitoringOuterClass {
  private EnvironmentalMonitoringOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      EnvironmentalMonitoringOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environmental_SensorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_environmental_SensorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environmental_SensorData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_environmental_SensorData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environmental_HistoricalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_environmental_HistoricalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environmental_HistoricalData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_environmental_HistoricalData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1src/main/resources/environmental_monit" +
      "oring.proto\022\renvironmental\"!\n\rSensorRequ" +
      "est\022\020\n\010location\030\001 \001(\t\"t\n\nSensorData\022\023\n\013t" +
      "emperature\030\001 \001(\002\022\020\n\010humidity\030\002 \001(\002\022\021\n\tco" +
      "2_level\030\003 \001(\005\022\031\n\021air_quality_index\030\004 \001(\005" +
      "\022\021\n\ttimestamp\030\005 \001(\003\":\n\021HistoricalRequest" +
      "\022\020\n\010location\030\001 \001(\t\022\023\n\013time_period\030\002 \001(\t\"" +
      "x\n\016HistoricalData\022\023\n\013temperature\030\001 \001(\002\022\020" +
      "\n\010humidity\030\002 \001(\002\022\021\n\tco2_level\030\003 \001(\005\022\031\n\021a" +
      "ir_quality_index\030\004 \001(\005\022\021\n\ttimestamp\030\005 \001(" +
      "\0032\267\001\n\027EnvironmentalMonitoring\022M\n\022GetCurr" +
      "entReadings\022\034.environmental.SensorReques" +
      "t\032\031.environmental.SensorData\022M\n\020StreamSe" +
      "nsorData\022\034.environmental.SensorRequest\032\031" +
      ".environmental.SensorData0\001B\024\n\020ds.enviro" +
      "nmentalP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_environmental_SensorRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_environmental_SensorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_environmental_SensorRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_environmental_SensorData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_environmental_SensorData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_environmental_SensorData_descriptor,
        new java.lang.String[] { "Temperature", "Humidity", "Co2Level", "AirQualityIndex", "Timestamp", });
    internal_static_environmental_HistoricalRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_environmental_HistoricalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_environmental_HistoricalRequest_descriptor,
        new java.lang.String[] { "Location", "TimePeriod", });
    internal_static_environmental_HistoricalData_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_environmental_HistoricalData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_environmental_HistoricalData_descriptor,
        new java.lang.String[] { "Temperature", "Humidity", "Co2Level", "AirQualityIndex", "Timestamp", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
