// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/environmental_monitoring.proto
// Protobuf Java Version: 4.31.1

package ds.environmental;

@com.google.protobuf.Generated
public interface HistoricalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:environmental.HistoricalRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string time_period = 2;</code>
   * @return The timePeriod.
   */
  java.lang.String getTimePeriod();
  /**
   * <code>string time_period = 2;</code>
   * @return The bytes for timePeriod.
   */
  com.google.protobuf.ByteString
      getTimePeriodBytes();
}
