// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/environmental_monitoring.proto
// Protobuf Java Version: 4.31.1

package ds.environmental;

@com.google.protobuf.Generated
public interface HistoricalDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:environmental.HistoricalData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float temperature = 1;</code>
   * @return The temperature.
   */
  float getTemperature();

  /**
   * <code>float humidity = 2;</code>
   * @return The humidity.
   */
  float getHumidity();

  /**
   * <code>int32 co2_level = 3;</code>
   * @return The co2Level.
   */
  int getCo2Level();

  /**
   * <code>int32 air_quality_index = 4;</code>
   * @return The airQualityIndex.
   */
  int getAirQualityIndex();

  /**
   * <code>int64 timestamp = 5;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
