// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/climate_analytics.proto
// Protobuf Java Version: 4.31.1

package ds.analytics;

@com.google.protobuf.Generated
public interface AnalysisResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:analytics.AnalysisResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float temperature_trend = 1;</code>
   * @return The temperatureTrend.
   */
  float getTemperatureTrend();

  /**
   * <code>string pollution_level = 2;</code>
   * @return The pollutionLevel.
   */
  java.lang.String getPollutionLevel();
  /**
   * <code>string pollution_level = 2;</code>
   * @return The bytes for pollutionLevel.
   */
  com.google.protobuf.ByteString
      getPollutionLevelBytes();

  /**
   * <code>repeated string recommendations = 3;</code>
   * @return A list containing the recommendations.
   */
  java.util.List<java.lang.String>
      getRecommendationsList();
  /**
   * <code>repeated string recommendations = 3;</code>
   * @return The count of recommendations.
   */
  int getRecommendationsCount();
  /**
   * <code>repeated string recommendations = 3;</code>
   * @param index The index of the element to return.
   * @return The recommendations at the given index.
   */
  java.lang.String getRecommendations(int index);
  /**
   * <code>repeated string recommendations = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the recommendations at the given index.
   */
  com.google.protobuf.ByteString
      getRecommendationsBytes(int index);

  /**
   * <code>float energy_efficiency_score = 4;</code>
   * @return The energyEfficiencyScore.
   */
  float getEnergyEfficiencyScore();
}
