// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/climate_analytics.proto
// Protobuf Java Version: 4.31.1

package ds.analytics;

/**
 * Protobuf type {@code analytics.AnalysisResult}
 */
@com.google.protobuf.Generated
public final class AnalysisResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:analytics.AnalysisResult)
    AnalysisResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      AnalysisResult.class.getName());
  }
  // Use AnalysisResult.newBuilder() to construct.
  private AnalysisResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AnalysisResult() {
    pollutionLevel_ = "";
    recommendations_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.analytics.ClimateAnalyticsOuterClass.internal_static_analytics_AnalysisResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.analytics.ClimateAnalyticsOuterClass.internal_static_analytics_AnalysisResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.analytics.AnalysisResult.class, ds.analytics.AnalysisResult.Builder.class);
  }

  public static final int TEMPERATURE_TREND_FIELD_NUMBER = 1;
  private float temperatureTrend_ = 0F;
  /**
   * <code>float temperature_trend = 1;</code>
   * @return The temperatureTrend.
   */
  @java.lang.Override
  public float getTemperatureTrend() {
    return temperatureTrend_;
  }

  public static final int POLLUTION_LEVEL_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pollutionLevel_ = "";
  /**
   * <code>string pollution_level = 2;</code>
   * @return The pollutionLevel.
   */
  @java.lang.Override
  public java.lang.String getPollutionLevel() {
    java.lang.Object ref = pollutionLevel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pollutionLevel_ = s;
      return s;
    }
  }
  /**
   * <code>string pollution_level = 2;</code>
   * @return The bytes for pollutionLevel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPollutionLevelBytes() {
    java.lang.Object ref = pollutionLevel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pollutionLevel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECOMMENDATIONS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList recommendations_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string recommendations = 3;</code>
   * @return A list containing the recommendations.
   */
  public com.google.protobuf.ProtocolStringList
      getRecommendationsList() {
    return recommendations_;
  }
  /**
   * <code>repeated string recommendations = 3;</code>
   * @return The count of recommendations.
   */
  public int getRecommendationsCount() {
    return recommendations_.size();
  }
  /**
   * <code>repeated string recommendations = 3;</code>
   * @param index The index of the element to return.
   * @return The recommendations at the given index.
   */
  public java.lang.String getRecommendations(int index) {
    return recommendations_.get(index);
  }
  /**
   * <code>repeated string recommendations = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the recommendations at the given index.
   */
  public com.google.protobuf.ByteString
      getRecommendationsBytes(int index) {
    return recommendations_.getByteString(index);
  }

  public static final int ENERGY_EFFICIENCY_SCORE_FIELD_NUMBER = 4;
  private float energyEfficiencyScore_ = 0F;
  /**
   * <code>float energy_efficiency_score = 4;</code>
   * @return The energyEfficiencyScore.
   */
  @java.lang.Override
  public float getEnergyEfficiencyScore() {
    return energyEfficiencyScore_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Float.floatToRawIntBits(temperatureTrend_) != 0) {
      output.writeFloat(1, temperatureTrend_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pollutionLevel_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, pollutionLevel_);
    }
    for (int i = 0; i < recommendations_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, recommendations_.getRaw(i));
    }
    if (java.lang.Float.floatToRawIntBits(energyEfficiencyScore_) != 0) {
      output.writeFloat(4, energyEfficiencyScore_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Float.floatToRawIntBits(temperatureTrend_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, temperatureTrend_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pollutionLevel_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, pollutionLevel_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < recommendations_.size(); i++) {
        dataSize += computeStringSizeNoTag(recommendations_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRecommendationsList().size();
    }
    if (java.lang.Float.floatToRawIntBits(energyEfficiencyScore_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, energyEfficiencyScore_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.analytics.AnalysisResult)) {
      return super.equals(obj);
    }
    ds.analytics.AnalysisResult other = (ds.analytics.AnalysisResult) obj;

    if (java.lang.Float.floatToIntBits(getTemperatureTrend())
        != java.lang.Float.floatToIntBits(
            other.getTemperatureTrend())) return false;
    if (!getPollutionLevel()
        .equals(other.getPollutionLevel())) return false;
    if (!getRecommendationsList()
        .equals(other.getRecommendationsList())) return false;
    if (java.lang.Float.floatToIntBits(getEnergyEfficiencyScore())
        != java.lang.Float.floatToIntBits(
            other.getEnergyEfficiencyScore())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEMPERATURE_TREND_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getTemperatureTrend());
    hash = (37 * hash) + POLLUTION_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getPollutionLevel().hashCode();
    if (getRecommendationsCount() > 0) {
      hash = (37 * hash) + RECOMMENDATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getRecommendationsList().hashCode();
    }
    hash = (37 * hash) + ENERGY_EFFICIENCY_SCORE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getEnergyEfficiencyScore());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.analytics.AnalysisResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.analytics.AnalysisResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.analytics.AnalysisResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.analytics.AnalysisResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.analytics.AnalysisResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.analytics.AnalysisResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.analytics.AnalysisResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ds.analytics.AnalysisResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ds.analytics.AnalysisResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ds.analytics.AnalysisResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.analytics.AnalysisResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ds.analytics.AnalysisResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.analytics.AnalysisResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code analytics.AnalysisResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:analytics.AnalysisResult)
      ds.analytics.AnalysisResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.analytics.ClimateAnalyticsOuterClass.internal_static_analytics_AnalysisResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.analytics.ClimateAnalyticsOuterClass.internal_static_analytics_AnalysisResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.analytics.AnalysisResult.class, ds.analytics.AnalysisResult.Builder.class);
    }

    // Construct using ds.analytics.AnalysisResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      temperatureTrend_ = 0F;
      pollutionLevel_ = "";
      recommendations_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      energyEfficiencyScore_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.analytics.ClimateAnalyticsOuterClass.internal_static_analytics_AnalysisResult_descriptor;
    }

    @java.lang.Override
    public ds.analytics.AnalysisResult getDefaultInstanceForType() {
      return ds.analytics.AnalysisResult.getDefaultInstance();
    }

    @java.lang.Override
    public ds.analytics.AnalysisResult build() {
      ds.analytics.AnalysisResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.analytics.AnalysisResult buildPartial() {
      ds.analytics.AnalysisResult result = new ds.analytics.AnalysisResult(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ds.analytics.AnalysisResult result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.temperatureTrend_ = temperatureTrend_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pollutionLevel_ = pollutionLevel_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        recommendations_.makeImmutable();
        result.recommendations_ = recommendations_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.energyEfficiencyScore_ = energyEfficiencyScore_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.analytics.AnalysisResult) {
        return mergeFrom((ds.analytics.AnalysisResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.analytics.AnalysisResult other) {
      if (other == ds.analytics.AnalysisResult.getDefaultInstance()) return this;
      if (java.lang.Float.floatToRawIntBits(other.getTemperatureTrend()) != 0) {
        setTemperatureTrend(other.getTemperatureTrend());
      }
      if (!other.getPollutionLevel().isEmpty()) {
        pollutionLevel_ = other.pollutionLevel_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.recommendations_.isEmpty()) {
        if (recommendations_.isEmpty()) {
          recommendations_ = other.recommendations_;
          bitField0_ |= 0x00000004;
        } else {
          ensureRecommendationsIsMutable();
          recommendations_.addAll(other.recommendations_);
        }
        onChanged();
      }
      if (java.lang.Float.floatToRawIntBits(other.getEnergyEfficiencyScore()) != 0) {
        setEnergyEfficiencyScore(other.getEnergyEfficiencyScore());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              temperatureTrend_ = input.readFloat();
              bitField0_ |= 0x00000001;
              break;
            } // case 13
            case 18: {
              pollutionLevel_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureRecommendationsIsMutable();
              recommendations_.add(s);
              break;
            } // case 26
            case 37: {
              energyEfficiencyScore_ = input.readFloat();
              bitField0_ |= 0x00000008;
              break;
            } // case 37
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private float temperatureTrend_ ;
    /**
     * <code>float temperature_trend = 1;</code>
     * @return The temperatureTrend.
     */
    @java.lang.Override
    public float getTemperatureTrend() {
      return temperatureTrend_;
    }
    /**
     * <code>float temperature_trend = 1;</code>
     * @param value The temperatureTrend to set.
     * @return This builder for chaining.
     */
    public Builder setTemperatureTrend(float value) {

      temperatureTrend_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>float temperature_trend = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTemperatureTrend() {
      bitField0_ = (bitField0_ & ~0x00000001);
      temperatureTrend_ = 0F;
      onChanged();
      return this;
    }

    private java.lang.Object pollutionLevel_ = "";
    /**
     * <code>string pollution_level = 2;</code>
     * @return The pollutionLevel.
     */
    public java.lang.String getPollutionLevel() {
      java.lang.Object ref = pollutionLevel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pollutionLevel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pollution_level = 2;</code>
     * @return The bytes for pollutionLevel.
     */
    public com.google.protobuf.ByteString
        getPollutionLevelBytes() {
      java.lang.Object ref = pollutionLevel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pollutionLevel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pollution_level = 2;</code>
     * @param value The pollutionLevel to set.
     * @return This builder for chaining.
     */
    public Builder setPollutionLevel(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pollutionLevel_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string pollution_level = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPollutionLevel() {
      pollutionLevel_ = getDefaultInstance().getPollutionLevel();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string pollution_level = 2;</code>
     * @param value The bytes for pollutionLevel to set.
     * @return This builder for chaining.
     */
    public Builder setPollutionLevelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pollutionLevel_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList recommendations_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureRecommendationsIsMutable() {
      if (!recommendations_.isModifiable()) {
        recommendations_ = new com.google.protobuf.LazyStringArrayList(recommendations_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>repeated string recommendations = 3;</code>
     * @return A list containing the recommendations.
     */
    public com.google.protobuf.ProtocolStringList
        getRecommendationsList() {
      recommendations_.makeImmutable();
      return recommendations_;
    }
    /**
     * <code>repeated string recommendations = 3;</code>
     * @return The count of recommendations.
     */
    public int getRecommendationsCount() {
      return recommendations_.size();
    }
    /**
     * <code>repeated string recommendations = 3;</code>
     * @param index The index of the element to return.
     * @return The recommendations at the given index.
     */
    public java.lang.String getRecommendations(int index) {
      return recommendations_.get(index);
    }
    /**
     * <code>repeated string recommendations = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the recommendations at the given index.
     */
    public com.google.protobuf.ByteString
        getRecommendationsBytes(int index) {
      return recommendations_.getByteString(index);
    }
    /**
     * <code>repeated string recommendations = 3;</code>
     * @param index The index to set the value at.
     * @param value The recommendations to set.
     * @return This builder for chaining.
     */
    public Builder setRecommendations(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureRecommendationsIsMutable();
      recommendations_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string recommendations = 3;</code>
     * @param value The recommendations to add.
     * @return This builder for chaining.
     */
    public Builder addRecommendations(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureRecommendationsIsMutable();
      recommendations_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string recommendations = 3;</code>
     * @param values The recommendations to add.
     * @return This builder for chaining.
     */
    public Builder addAllRecommendations(
        java.lang.Iterable<java.lang.String> values) {
      ensureRecommendationsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, recommendations_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string recommendations = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecommendations() {
      recommendations_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string recommendations = 3;</code>
     * @param value The bytes of the recommendations to add.
     * @return This builder for chaining.
     */
    public Builder addRecommendationsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureRecommendationsIsMutable();
      recommendations_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private float energyEfficiencyScore_ ;
    /**
     * <code>float energy_efficiency_score = 4;</code>
     * @return The energyEfficiencyScore.
     */
    @java.lang.Override
    public float getEnergyEfficiencyScore() {
      return energyEfficiencyScore_;
    }
    /**
     * <code>float energy_efficiency_score = 4;</code>
     * @param value The energyEfficiencyScore to set.
     * @return This builder for chaining.
     */
    public Builder setEnergyEfficiencyScore(float value) {

      energyEfficiencyScore_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>float energy_efficiency_score = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnergyEfficiencyScore() {
      bitField0_ = (bitField0_ & ~0x00000008);
      energyEfficiencyScore_ = 0F;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:analytics.AnalysisResult)
  }

  // @@protoc_insertion_point(class_scope:analytics.AnalysisResult)
  private static final ds.analytics.AnalysisResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.analytics.AnalysisResult();
  }

  public static ds.analytics.AnalysisResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnalysisResult>
      PARSER = new com.google.protobuf.AbstractParser<AnalysisResult>() {
    @java.lang.Override
    public AnalysisResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AnalysisResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AnalysisResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.analytics.AnalysisResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

