// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/climate_analytics.proto
// Protobuf Java Version: 4.31.1

package ds.analytics;

/**
 * Protobuf type {@code analytics.AnalysisRequest}
 */
@com.google.protobuf.Generated
public final class AnalysisRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:analytics.AnalysisRequest)
    AnalysisRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      AnalysisRequest.class.getName());
  }
  // Use AnalysisRequest.newBuilder() to construct.
  private AnalysisRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AnalysisRequest() {
    timePeriod_ = "";
    dataTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    location_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.analytics.ClimateAnalyticsOuterClass.internal_static_analytics_AnalysisRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.analytics.ClimateAnalyticsOuterClass.internal_static_analytics_AnalysisRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.analytics.AnalysisRequest.class, ds.analytics.AnalysisRequest.Builder.class);
  }

  public static final int TIME_PERIOD_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object timePeriod_ = "";
  /**
   * <code>string time_period = 1;</code>
   * @return The timePeriod.
   */
  @java.lang.Override
  public java.lang.String getTimePeriod() {
    java.lang.Object ref = timePeriod_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timePeriod_ = s;
      return s;
    }
  }
  /**
   * <code>string time_period = 1;</code>
   * @return The bytes for timePeriod.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimePeriodBytes() {
    java.lang.Object ref = timePeriod_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timePeriod_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_TYPES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList dataTypes_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string data_types = 2;</code>
   * @return A list containing the dataTypes.
   */
  public com.google.protobuf.ProtocolStringList
      getDataTypesList() {
    return dataTypes_;
  }
  /**
   * <code>repeated string data_types = 2;</code>
   * @return The count of dataTypes.
   */
  public int getDataTypesCount() {
    return dataTypes_.size();
  }
  /**
   * <code>repeated string data_types = 2;</code>
   * @param index The index of the element to return.
   * @return The dataTypes at the given index.
   */
  public java.lang.String getDataTypes(int index) {
    return dataTypes_.get(index);
  }
  /**
   * <code>repeated string data_types = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the dataTypes at the given index.
   */
  public com.google.protobuf.ByteString
      getDataTypesBytes(int index) {
    return dataTypes_.getByteString(index);
  }

  public static final int LOCATION_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object location_ = "";
  /**
   * <code>string location = 3;</code>
   * @return The location.
   */
  @java.lang.Override
  public java.lang.String getLocation() {
    java.lang.Object ref = location_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      location_ = s;
      return s;
    }
  }
  /**
   * <code>string location = 3;</code>
   * @return The bytes for location.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLocationBytes() {
    java.lang.Object ref = location_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      location_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(timePeriod_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, timePeriod_);
    }
    for (int i = 0; i < dataTypes_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, dataTypes_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(location_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, location_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(timePeriod_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, timePeriod_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < dataTypes_.size(); i++) {
        dataSize += computeStringSizeNoTag(dataTypes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDataTypesList().size();
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(location_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, location_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.analytics.AnalysisRequest)) {
      return super.equals(obj);
    }
    ds.analytics.AnalysisRequest other = (ds.analytics.AnalysisRequest) obj;

    if (!getTimePeriod()
        .equals(other.getTimePeriod())) return false;
    if (!getDataTypesList()
        .equals(other.getDataTypesList())) return false;
    if (!getLocation()
        .equals(other.getLocation())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIME_PERIOD_FIELD_NUMBER;
    hash = (53 * hash) + getTimePeriod().hashCode();
    if (getDataTypesCount() > 0) {
      hash = (37 * hash) + DATA_TYPES_FIELD_NUMBER;
      hash = (53 * hash) + getDataTypesList().hashCode();
    }
    hash = (37 * hash) + LOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getLocation().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.analytics.AnalysisRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.analytics.AnalysisRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.analytics.AnalysisRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.analytics.AnalysisRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.analytics.AnalysisRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.analytics.AnalysisRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.analytics.AnalysisRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ds.analytics.AnalysisRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ds.analytics.AnalysisRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ds.analytics.AnalysisRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.analytics.AnalysisRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ds.analytics.AnalysisRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.analytics.AnalysisRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code analytics.AnalysisRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:analytics.AnalysisRequest)
      ds.analytics.AnalysisRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.analytics.ClimateAnalyticsOuterClass.internal_static_analytics_AnalysisRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.analytics.ClimateAnalyticsOuterClass.internal_static_analytics_AnalysisRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.analytics.AnalysisRequest.class, ds.analytics.AnalysisRequest.Builder.class);
    }

    // Construct using ds.analytics.AnalysisRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      timePeriod_ = "";
      dataTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      location_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.analytics.ClimateAnalyticsOuterClass.internal_static_analytics_AnalysisRequest_descriptor;
    }

    @java.lang.Override
    public ds.analytics.AnalysisRequest getDefaultInstanceForType() {
      return ds.analytics.AnalysisRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ds.analytics.AnalysisRequest build() {
      ds.analytics.AnalysisRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.analytics.AnalysisRequest buildPartial() {
      ds.analytics.AnalysisRequest result = new ds.analytics.AnalysisRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ds.analytics.AnalysisRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.timePeriod_ = timePeriod_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        dataTypes_.makeImmutable();
        result.dataTypes_ = dataTypes_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.location_ = location_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.analytics.AnalysisRequest) {
        return mergeFrom((ds.analytics.AnalysisRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.analytics.AnalysisRequest other) {
      if (other == ds.analytics.AnalysisRequest.getDefaultInstance()) return this;
      if (!other.getTimePeriod().isEmpty()) {
        timePeriod_ = other.timePeriod_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.dataTypes_.isEmpty()) {
        if (dataTypes_.isEmpty()) {
          dataTypes_ = other.dataTypes_;
          bitField0_ |= 0x00000002;
        } else {
          ensureDataTypesIsMutable();
          dataTypes_.addAll(other.dataTypes_);
        }
        onChanged();
      }
      if (!other.getLocation().isEmpty()) {
        location_ = other.location_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              timePeriod_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureDataTypesIsMutable();
              dataTypes_.add(s);
              break;
            } // case 18
            case 26: {
              location_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object timePeriod_ = "";
    /**
     * <code>string time_period = 1;</code>
     * @return The timePeriod.
     */
    public java.lang.String getTimePeriod() {
      java.lang.Object ref = timePeriod_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timePeriod_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string time_period = 1;</code>
     * @return The bytes for timePeriod.
     */
    public com.google.protobuf.ByteString
        getTimePeriodBytes() {
      java.lang.Object ref = timePeriod_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timePeriod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string time_period = 1;</code>
     * @param value The timePeriod to set.
     * @return This builder for chaining.
     */
    public Builder setTimePeriod(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      timePeriod_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string time_period = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimePeriod() {
      timePeriod_ = getDefaultInstance().getTimePeriod();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string time_period = 1;</code>
     * @param value The bytes for timePeriod to set.
     * @return This builder for chaining.
     */
    public Builder setTimePeriodBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      timePeriod_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList dataTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureDataTypesIsMutable() {
      if (!dataTypes_.isModifiable()) {
        dataTypes_ = new com.google.protobuf.LazyStringArrayList(dataTypes_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated string data_types = 2;</code>
     * @return A list containing the dataTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getDataTypesList() {
      dataTypes_.makeImmutable();
      return dataTypes_;
    }
    /**
     * <code>repeated string data_types = 2;</code>
     * @return The count of dataTypes.
     */
    public int getDataTypesCount() {
      return dataTypes_.size();
    }
    /**
     * <code>repeated string data_types = 2;</code>
     * @param index The index of the element to return.
     * @return The dataTypes at the given index.
     */
    public java.lang.String getDataTypes(int index) {
      return dataTypes_.get(index);
    }
    /**
     * <code>repeated string data_types = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the dataTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getDataTypesBytes(int index) {
      return dataTypes_.getByteString(index);
    }
    /**
     * <code>repeated string data_types = 2;</code>
     * @param index The index to set the value at.
     * @param value The dataTypes to set.
     * @return This builder for chaining.
     */
    public Builder setDataTypes(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureDataTypesIsMutable();
      dataTypes_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string data_types = 2;</code>
     * @param value The dataTypes to add.
     * @return This builder for chaining.
     */
    public Builder addDataTypes(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureDataTypesIsMutable();
      dataTypes_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string data_types = 2;</code>
     * @param values The dataTypes to add.
     * @return This builder for chaining.
     */
    public Builder addAllDataTypes(
        java.lang.Iterable<java.lang.String> values) {
      ensureDataTypesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, dataTypes_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string data_types = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataTypes() {
      dataTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string data_types = 2;</code>
     * @param value The bytes of the dataTypes to add.
     * @return This builder for chaining.
     */
    public Builder addDataTypesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureDataTypesIsMutable();
      dataTypes_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object location_ = "";
    /**
     * <code>string location = 3;</code>
     * @return The location.
     */
    public java.lang.String getLocation() {
      java.lang.Object ref = location_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        location_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string location = 3;</code>
     * @return The bytes for location.
     */
    public com.google.protobuf.ByteString
        getLocationBytes() {
      java.lang.Object ref = location_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        location_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string location = 3;</code>
     * @param value The location to set.
     * @return This builder for chaining.
     */
    public Builder setLocation(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      location_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string location = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocation() {
      location_ = getDefaultInstance().getLocation();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string location = 3;</code>
     * @param value The bytes for location to set.
     * @return This builder for chaining.
     */
    public Builder setLocationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      location_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:analytics.AnalysisRequest)
  }

  // @@protoc_insertion_point(class_scope:analytics.AnalysisRequest)
  private static final ds.analytics.AnalysisRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.analytics.AnalysisRequest();
  }

  public static ds.analytics.AnalysisRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnalysisRequest>
      PARSER = new com.google.protobuf.AbstractParser<AnalysisRequest>() {
    @java.lang.Override
    public AnalysisRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AnalysisRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AnalysisRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.analytics.AnalysisRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

