// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/climate_analytics.proto
// Protobuf Java Version: 4.31.1

package ds.analytics;

@com.google.protobuf.Generated
public interface AnalysisRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:analytics.AnalysisRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string time_period = 1;</code>
   * @return The timePeriod.
   */
  java.lang.String getTimePeriod();
  /**
   * <code>string time_period = 1;</code>
   * @return The bytes for timePeriod.
   */
  com.google.protobuf.ByteString
      getTimePeriodBytes();

  /**
   * <code>repeated string data_types = 2;</code>
   * @return A list containing the dataTypes.
   */
  java.util.List<java.lang.String>
      getDataTypesList();
  /**
   * <code>repeated string data_types = 2;</code>
   * @return The count of dataTypes.
   */
  int getDataTypesCount();
  /**
   * <code>repeated string data_types = 2;</code>
   * @param index The index of the element to return.
   * @return The dataTypes at the given index.
   */
  java.lang.String getDataTypes(int index);
  /**
   * <code>repeated string data_types = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the dataTypes at the given index.
   */
  com.google.protobuf.ByteString
      getDataTypesBytes(int index);

  /**
   * <code>string location = 3;</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 3;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
