// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/climate_analytics.proto
// Protobuf Java Version: 4.31.1

package ds.analytics;

@com.google.protobuf.Generated
public final class ClimateAnalyticsOuterClass {
  private ClimateAnalyticsOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      ClimateAnalyticsOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_analytics_AnalysisRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_analytics_AnalysisRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_analytics_AnalysisResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_analytics_AnalysisResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_analytics_AnalysisData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_analytics_AnalysisData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*src/main/resources/climate_analytics.p" +
      "roto\022\tanalytics\"L\n\017AnalysisRequest\022\023\n\013ti" +
      "me_period\030\001 \001(\t\022\022\n\ndata_types\030\002 \003(\t\022\020\n\010l" +
      "ocation\030\003 \001(\t\"~\n\016AnalysisResult\022\031\n\021tempe" +
      "rature_trend\030\001 \001(\002\022\027\n\017pollution_level\030\002 " +
      "\001(\t\022\027\n\017recommendations\030\003 \003(\t\022\037\n\027energy_e" +
      "fficiency_score\030\004 \001(\002\"\210\001\n\014AnalysisData\022\023" +
      "\n\013temperature\030\001 \001(\002\022\020\n\010humidity\030\002 \001(\002\022\021\n" +
      "\tco2_level\030\003 \001(\005\022\031\n\021air_quality_index\030\004 " +
      "\001(\005\022\021\n\ttimestamp\030\005 \001(\003\022\020\n\010location\030\006 \001(\t" +
      "2\253\001\n\020ClimateAnalytics\022K\n\022AnalyzeClimateD" +
      "ata\022\032.analytics.AnalysisRequest\032\031.analyt" +
      "ics.AnalysisResult\022J\n\020RealTimeAnalysis\022\027" +
      ".analytics.AnalysisData\032\031.analytics.Anal" +
      "ysisResult(\0010\001B\020\n\014ds.analyticsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_analytics_AnalysisRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_analytics_AnalysisRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_analytics_AnalysisRequest_descriptor,
        new java.lang.String[] { "TimePeriod", "DataTypes", "Location", });
    internal_static_analytics_AnalysisResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_analytics_AnalysisResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_analytics_AnalysisResult_descriptor,
        new java.lang.String[] { "TemperatureTrend", "PollutionLevel", "Recommendations", "EnergyEfficiencyScore", });
    internal_static_analytics_AnalysisData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_analytics_AnalysisData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_analytics_AnalysisData_descriptor,
        new java.lang.String[] { "Temperature", "Humidity", "Co2Level", "AirQualityIndex", "Timestamp", "Location", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
