// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/climate_response.proto
// Protobuf Java Version: 4.31.1

package ds.response;

/**
 * Protobuf type {@code response.BatchCommandResponse}
 */
@com.google.protobuf.Generated
public final class BatchCommandResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:response.BatchCommandResponse)
    BatchCommandResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      BatchCommandResponse.class.getName());
  }
  // Use BatchCommandResponse.newBuilder() to construct.
  private BatchCommandResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BatchCommandResponse() {
    overallStatus_ = "";
    deviceStatuses_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.response.ClimateResponseOuterClass.internal_static_response_BatchCommandResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.response.ClimateResponseOuterClass.internal_static_response_BatchCommandResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.response.BatchCommandResponse.class, ds.response.BatchCommandResponse.Builder.class);
  }

  public static final int COMMANDS_PROCESSED_FIELD_NUMBER = 1;
  private int commandsProcessed_ = 0;
  /**
   * <code>int32 commands_processed = 1;</code>
   * @return The commandsProcessed.
   */
  @java.lang.Override
  public int getCommandsProcessed() {
    return commandsProcessed_;
  }

  public static final int OVERALL_STATUS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object overallStatus_ = "";
  /**
   * <code>string overall_status = 2;</code>
   * @return The overallStatus.
   */
  @java.lang.Override
  public java.lang.String getOverallStatus() {
    java.lang.Object ref = overallStatus_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      overallStatus_ = s;
      return s;
    }
  }
  /**
   * <code>string overall_status = 2;</code>
   * @return The bytes for overallStatus.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOverallStatusBytes() {
    java.lang.Object ref = overallStatus_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      overallStatus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICE_STATUSES_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<ds.response.DeviceStatus> deviceStatuses_;
  /**
   * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
   */
  @java.lang.Override
  public java.util.List<ds.response.DeviceStatus> getDeviceStatusesList() {
    return deviceStatuses_;
  }
  /**
   * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ds.response.DeviceStatusOrBuilder> 
      getDeviceStatusesOrBuilderList() {
    return deviceStatuses_;
  }
  /**
   * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
   */
  @java.lang.Override
  public int getDeviceStatusesCount() {
    return deviceStatuses_.size();
  }
  /**
   * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
   */
  @java.lang.Override
  public ds.response.DeviceStatus getDeviceStatuses(int index) {
    return deviceStatuses_.get(index);
  }
  /**
   * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
   */
  @java.lang.Override
  public ds.response.DeviceStatusOrBuilder getDeviceStatusesOrBuilder(
      int index) {
    return deviceStatuses_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (commandsProcessed_ != 0) {
      output.writeInt32(1, commandsProcessed_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(overallStatus_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, overallStatus_);
    }
    for (int i = 0; i < deviceStatuses_.size(); i++) {
      output.writeMessage(3, deviceStatuses_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (commandsProcessed_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, commandsProcessed_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(overallStatus_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, overallStatus_);
    }
    for (int i = 0; i < deviceStatuses_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, deviceStatuses_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.response.BatchCommandResponse)) {
      return super.equals(obj);
    }
    ds.response.BatchCommandResponse other = (ds.response.BatchCommandResponse) obj;

    if (getCommandsProcessed()
        != other.getCommandsProcessed()) return false;
    if (!getOverallStatus()
        .equals(other.getOverallStatus())) return false;
    if (!getDeviceStatusesList()
        .equals(other.getDeviceStatusesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMANDS_PROCESSED_FIELD_NUMBER;
    hash = (53 * hash) + getCommandsProcessed();
    hash = (37 * hash) + OVERALL_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getOverallStatus().hashCode();
    if (getDeviceStatusesCount() > 0) {
      hash = (37 * hash) + DEVICE_STATUSES_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceStatusesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.response.BatchCommandResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.response.BatchCommandResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.response.BatchCommandResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.response.BatchCommandResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.response.BatchCommandResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.response.BatchCommandResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.response.BatchCommandResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ds.response.BatchCommandResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ds.response.BatchCommandResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ds.response.BatchCommandResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.response.BatchCommandResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ds.response.BatchCommandResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.response.BatchCommandResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code response.BatchCommandResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:response.BatchCommandResponse)
      ds.response.BatchCommandResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.response.ClimateResponseOuterClass.internal_static_response_BatchCommandResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.response.ClimateResponseOuterClass.internal_static_response_BatchCommandResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.response.BatchCommandResponse.class, ds.response.BatchCommandResponse.Builder.class);
    }

    // Construct using ds.response.BatchCommandResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      commandsProcessed_ = 0;
      overallStatus_ = "";
      if (deviceStatusesBuilder_ == null) {
        deviceStatuses_ = java.util.Collections.emptyList();
      } else {
        deviceStatuses_ = null;
        deviceStatusesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.response.ClimateResponseOuterClass.internal_static_response_BatchCommandResponse_descriptor;
    }

    @java.lang.Override
    public ds.response.BatchCommandResponse getDefaultInstanceForType() {
      return ds.response.BatchCommandResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.response.BatchCommandResponse build() {
      ds.response.BatchCommandResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.response.BatchCommandResponse buildPartial() {
      ds.response.BatchCommandResponse result = new ds.response.BatchCommandResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(ds.response.BatchCommandResponse result) {
      if (deviceStatusesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          deviceStatuses_ = java.util.Collections.unmodifiableList(deviceStatuses_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.deviceStatuses_ = deviceStatuses_;
      } else {
        result.deviceStatuses_ = deviceStatusesBuilder_.build();
      }
    }

    private void buildPartial0(ds.response.BatchCommandResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.commandsProcessed_ = commandsProcessed_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.overallStatus_ = overallStatus_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.response.BatchCommandResponse) {
        return mergeFrom((ds.response.BatchCommandResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.response.BatchCommandResponse other) {
      if (other == ds.response.BatchCommandResponse.getDefaultInstance()) return this;
      if (other.getCommandsProcessed() != 0) {
        setCommandsProcessed(other.getCommandsProcessed());
      }
      if (!other.getOverallStatus().isEmpty()) {
        overallStatus_ = other.overallStatus_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (deviceStatusesBuilder_ == null) {
        if (!other.deviceStatuses_.isEmpty()) {
          if (deviceStatuses_.isEmpty()) {
            deviceStatuses_ = other.deviceStatuses_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDeviceStatusesIsMutable();
            deviceStatuses_.addAll(other.deviceStatuses_);
          }
          onChanged();
        }
      } else {
        if (!other.deviceStatuses_.isEmpty()) {
          if (deviceStatusesBuilder_.isEmpty()) {
            deviceStatusesBuilder_.dispose();
            deviceStatusesBuilder_ = null;
            deviceStatuses_ = other.deviceStatuses_;
            bitField0_ = (bitField0_ & ~0x00000004);
            deviceStatusesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetDeviceStatusesFieldBuilder() : null;
          } else {
            deviceStatusesBuilder_.addAllMessages(other.deviceStatuses_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              commandsProcessed_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              overallStatus_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              ds.response.DeviceStatus m =
                  input.readMessage(
                      ds.response.DeviceStatus.parser(),
                      extensionRegistry);
              if (deviceStatusesBuilder_ == null) {
                ensureDeviceStatusesIsMutable();
                deviceStatuses_.add(m);
              } else {
                deviceStatusesBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int commandsProcessed_ ;
    /**
     * <code>int32 commands_processed = 1;</code>
     * @return The commandsProcessed.
     */
    @java.lang.Override
    public int getCommandsProcessed() {
      return commandsProcessed_;
    }
    /**
     * <code>int32 commands_processed = 1;</code>
     * @param value The commandsProcessed to set.
     * @return This builder for chaining.
     */
    public Builder setCommandsProcessed(int value) {

      commandsProcessed_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 commands_processed = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommandsProcessed() {
      bitField0_ = (bitField0_ & ~0x00000001);
      commandsProcessed_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object overallStatus_ = "";
    /**
     * <code>string overall_status = 2;</code>
     * @return The overallStatus.
     */
    public java.lang.String getOverallStatus() {
      java.lang.Object ref = overallStatus_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        overallStatus_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string overall_status = 2;</code>
     * @return The bytes for overallStatus.
     */
    public com.google.protobuf.ByteString
        getOverallStatusBytes() {
      java.lang.Object ref = overallStatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        overallStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string overall_status = 2;</code>
     * @param value The overallStatus to set.
     * @return This builder for chaining.
     */
    public Builder setOverallStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      overallStatus_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string overall_status = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOverallStatus() {
      overallStatus_ = getDefaultInstance().getOverallStatus();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string overall_status = 2;</code>
     * @param value The bytes for overallStatus to set.
     * @return This builder for chaining.
     */
    public Builder setOverallStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      overallStatus_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<ds.response.DeviceStatus> deviceStatuses_ =
      java.util.Collections.emptyList();
    private void ensureDeviceStatusesIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        deviceStatuses_ = new java.util.ArrayList<ds.response.DeviceStatus>(deviceStatuses_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        ds.response.DeviceStatus, ds.response.DeviceStatus.Builder, ds.response.DeviceStatusOrBuilder> deviceStatusesBuilder_;

    /**
     * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
     */
    public java.util.List<ds.response.DeviceStatus> getDeviceStatusesList() {
      if (deviceStatusesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(deviceStatuses_);
      } else {
        return deviceStatusesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
     */
    public int getDeviceStatusesCount() {
      if (deviceStatusesBuilder_ == null) {
        return deviceStatuses_.size();
      } else {
        return deviceStatusesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
     */
    public ds.response.DeviceStatus getDeviceStatuses(int index) {
      if (deviceStatusesBuilder_ == null) {
        return deviceStatuses_.get(index);
      } else {
        return deviceStatusesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
     */
    public Builder setDeviceStatuses(
        int index, ds.response.DeviceStatus value) {
      if (deviceStatusesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeviceStatusesIsMutable();
        deviceStatuses_.set(index, value);
        onChanged();
      } else {
        deviceStatusesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
     */
    public Builder setDeviceStatuses(
        int index, ds.response.DeviceStatus.Builder builderForValue) {
      if (deviceStatusesBuilder_ == null) {
        ensureDeviceStatusesIsMutable();
        deviceStatuses_.set(index, builderForValue.build());
        onChanged();
      } else {
        deviceStatusesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
     */
    public Builder addDeviceStatuses(ds.response.DeviceStatus value) {
      if (deviceStatusesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeviceStatusesIsMutable();
        deviceStatuses_.add(value);
        onChanged();
      } else {
        deviceStatusesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
     */
    public Builder addDeviceStatuses(
        int index, ds.response.DeviceStatus value) {
      if (deviceStatusesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeviceStatusesIsMutable();
        deviceStatuses_.add(index, value);
        onChanged();
      } else {
        deviceStatusesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
     */
    public Builder addDeviceStatuses(
        ds.response.DeviceStatus.Builder builderForValue) {
      if (deviceStatusesBuilder_ == null) {
        ensureDeviceStatusesIsMutable();
        deviceStatuses_.add(builderForValue.build());
        onChanged();
      } else {
        deviceStatusesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
     */
    public Builder addDeviceStatuses(
        int index, ds.response.DeviceStatus.Builder builderForValue) {
      if (deviceStatusesBuilder_ == null) {
        ensureDeviceStatusesIsMutable();
        deviceStatuses_.add(index, builderForValue.build());
        onChanged();
      } else {
        deviceStatusesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
     */
    public Builder addAllDeviceStatuses(
        java.lang.Iterable<? extends ds.response.DeviceStatus> values) {
      if (deviceStatusesBuilder_ == null) {
        ensureDeviceStatusesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, deviceStatuses_);
        onChanged();
      } else {
        deviceStatusesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
     */
    public Builder clearDeviceStatuses() {
      if (deviceStatusesBuilder_ == null) {
        deviceStatuses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        deviceStatusesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
     */
    public Builder removeDeviceStatuses(int index) {
      if (deviceStatusesBuilder_ == null) {
        ensureDeviceStatusesIsMutable();
        deviceStatuses_.remove(index);
        onChanged();
      } else {
        deviceStatusesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
     */
    public ds.response.DeviceStatus.Builder getDeviceStatusesBuilder(
        int index) {
      return internalGetDeviceStatusesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
     */
    public ds.response.DeviceStatusOrBuilder getDeviceStatusesOrBuilder(
        int index) {
      if (deviceStatusesBuilder_ == null) {
        return deviceStatuses_.get(index);  } else {
        return deviceStatusesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
     */
    public java.util.List<? extends ds.response.DeviceStatusOrBuilder> 
         getDeviceStatusesOrBuilderList() {
      if (deviceStatusesBuilder_ != null) {
        return deviceStatusesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(deviceStatuses_);
      }
    }
    /**
     * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
     */
    public ds.response.DeviceStatus.Builder addDeviceStatusesBuilder() {
      return internalGetDeviceStatusesFieldBuilder().addBuilder(
          ds.response.DeviceStatus.getDefaultInstance());
    }
    /**
     * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
     */
    public ds.response.DeviceStatus.Builder addDeviceStatusesBuilder(
        int index) {
      return internalGetDeviceStatusesFieldBuilder().addBuilder(
          index, ds.response.DeviceStatus.getDefaultInstance());
    }
    /**
     * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
     */
    public java.util.List<ds.response.DeviceStatus.Builder> 
         getDeviceStatusesBuilderList() {
      return internalGetDeviceStatusesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        ds.response.DeviceStatus, ds.response.DeviceStatus.Builder, ds.response.DeviceStatusOrBuilder> 
        internalGetDeviceStatusesFieldBuilder() {
      if (deviceStatusesBuilder_ == null) {
        deviceStatusesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            ds.response.DeviceStatus, ds.response.DeviceStatus.Builder, ds.response.DeviceStatusOrBuilder>(
                deviceStatuses_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        deviceStatuses_ = null;
      }
      return deviceStatusesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:response.BatchCommandResponse)
  }

  // @@protoc_insertion_point(class_scope:response.BatchCommandResponse)
  private static final ds.response.BatchCommandResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.response.BatchCommandResponse();
  }

  public static ds.response.BatchCommandResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BatchCommandResponse>
      PARSER = new com.google.protobuf.AbstractParser<BatchCommandResponse>() {
    @java.lang.Override
    public BatchCommandResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BatchCommandResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BatchCommandResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.response.BatchCommandResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

