// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/climate_response.proto
// Protobuf Java Version: 4.31.1

package ds.response;

@com.google.protobuf.Generated
public interface BatchCommandResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:response.BatchCommandResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 commands_processed = 1;</code>
   * @return The commandsProcessed.
   */
  int getCommandsProcessed();

  /**
   * <code>string overall_status = 2;</code>
   * @return The overallStatus.
   */
  java.lang.String getOverallStatus();
  /**
   * <code>string overall_status = 2;</code>
   * @return The bytes for overallStatus.
   */
  com.google.protobuf.ByteString
      getOverallStatusBytes();

  /**
   * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
   */
  java.util.List<ds.response.DeviceStatus> 
      getDeviceStatusesList();
  /**
   * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
   */
  ds.response.DeviceStatus getDeviceStatuses(int index);
  /**
   * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
   */
  int getDeviceStatusesCount();
  /**
   * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
   */
  java.util.List<? extends ds.response.DeviceStatusOrBuilder> 
      getDeviceStatusesOrBuilderList();
  /**
   * <code>repeated .response.DeviceStatus device_statuses = 3;</code>
   */
  ds.response.DeviceStatusOrBuilder getDeviceStatusesOrBuilder(
      int index);
}
