// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/climate_response.proto
// Protobuf Java Version: 4.31.1

package ds.response;

@com.google.protobuf.Generated
public final class ClimateResponseOuterClass {
  private ClimateResponseOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      ClimateResponseOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_response_DeviceCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_response_DeviceCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_response_DeviceStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_response_DeviceStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_response_BatchCommandResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_response_BatchCommandResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)src/main/resources/climate_response.pr" +
      "oto\022\010response\"Q\n\rDeviceCommand\022\021\n\tdevice" +
      "_id\030\001 \001(\t\022\027\n\017intensity_level\030\002 \001(\005\022\024\n\014co" +
      "mmand_type\030\003 \001(\t\"c\n\014DeviceStatus\022\021\n\tdevi" +
      "ce_id\030\001 \001(\t\022\021\n\tis_active\030\002 \001(\010\022\025\n\rcurren" +
      "t_level\030\003 \001(\005\022\026\n\016status_message\030\004 \001(\t\"{\n" +
      "\024BatchCommandResponse\022\032\n\022commands_proces" +
      "sed\030\001 \001(\005\022\026\n\016overall_status\030\002 \001(\t\022/\n\017dev" +
      "ice_statuses\030\003 \003(\0132\026.response.DeviceStat" +
      "us2\250\001\n\017ClimateResponse\022A\n\016ActivateDevice" +
      "\022\027.response.DeviceCommand\032\026.response.Dev" +
      "iceStatus\022R\n\025ProcessDeviceCommands\022\027.res" +
      "ponse.DeviceCommand\032\036.response.BatchComm" +
      "andResponse(\001B\017\n\013ds.responseP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_response_DeviceCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_response_DeviceCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_response_DeviceCommand_descriptor,
        new java.lang.String[] { "DeviceId", "IntensityLevel", "CommandType", });
    internal_static_response_DeviceStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_response_DeviceStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_response_DeviceStatus_descriptor,
        new java.lang.String[] { "DeviceId", "IsActive", "CurrentLevel", "StatusMessage", });
    internal_static_response_BatchCommandResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_response_BatchCommandResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_response_BatchCommandResponse_descriptor,
        new java.lang.String[] { "CommandsProcessed", "OverallStatus", "DeviceStatuses", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
