// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/climate_response.proto
// Protobuf Java Version: 4.31.1

package ds.response;

@com.google.protobuf.Generated
public interface DeviceStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:response.DeviceStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string device_id = 1;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 1;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>bool is_active = 2;</code>
   * @return The isActive.
   */
  boolean getIsActive();

  /**
   * <code>int32 current_level = 3;</code>
   * @return The currentLevel.
   */
  int getCurrentLevel();

  /**
   * <code>string status_message = 4;</code>
   * @return The statusMessage.
   */
  java.lang.String getStatusMessage();
  /**
   * <code>string status_message = 4;</code>
   * @return The bytes for statusMessage.
   */
  com.google.protobuf.ByteString
      getStatusMessageBytes();
}
