// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/climate_response.proto
// Protobuf Java Version: 4.31.1

package ds.response;

@com.google.protobuf.Generated
public interface DeviceCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:response.DeviceCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string device_id = 1;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 1;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>int32 intensity_level = 2;</code>
   * @return The intensityLevel.
   */
  int getIntensityLevel();

  /**
   * <pre>
   * "activate", "deactivate", "adjust"
   * </pre>
   *
   * <code>string command_type = 3;</code>
   * @return The commandType.
   */
  java.lang.String getCommandType();
  /**
   * <pre>
   * "activate", "deactivate", "adjust"
   * </pre>
   *
   * <code>string command_type = 3;</code>
   * @return The bytes for commandType.
   */
  com.google.protobuf.ByteString
      getCommandTypeBytes();
}
