// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/climate_response.proto
// Protobuf Java Version: 4.31.1

package ds.response;

/**
 * Protobuf type {@code response.DeviceCommand}
 */
@com.google.protobuf.Generated
public final class DeviceCommand extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:response.DeviceCommand)
    DeviceCommandOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      DeviceCommand.class.getName());
  }
  // Use DeviceCommand.newBuilder() to construct.
  private DeviceCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DeviceCommand() {
    deviceId_ = "";
    commandType_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.response.ClimateResponseOuterClass.internal_static_response_DeviceCommand_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.response.ClimateResponseOuterClass.internal_static_response_DeviceCommand_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.response.DeviceCommand.class, ds.response.DeviceCommand.Builder.class);
  }

  public static final int DEVICE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object deviceId_ = "";
  /**
   * <code>string device_id = 1;</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceId_ = s;
      return s;
    }
  }
  /**
   * <code>string device_id = 1;</code>
   * @return The bytes for deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTENSITY_LEVEL_FIELD_NUMBER = 2;
  private int intensityLevel_ = 0;
  /**
   * <code>int32 intensity_level = 2;</code>
   * @return The intensityLevel.
   */
  @java.lang.Override
  public int getIntensityLevel() {
    return intensityLevel_;
  }

  public static final int COMMAND_TYPE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object commandType_ = "";
  /**
   * <pre>
   * "activate", "deactivate", "adjust"
   * </pre>
   *
   * <code>string command_type = 3;</code>
   * @return The commandType.
   */
  @java.lang.Override
  public java.lang.String getCommandType() {
    java.lang.Object ref = commandType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      commandType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "activate", "deactivate", "adjust"
   * </pre>
   *
   * <code>string command_type = 3;</code>
   * @return The bytes for commandType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommandTypeBytes() {
    java.lang.Object ref = commandType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      commandType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deviceId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, deviceId_);
    }
    if (intensityLevel_ != 0) {
      output.writeInt32(2, intensityLevel_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(commandType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, commandType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deviceId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, deviceId_);
    }
    if (intensityLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, intensityLevel_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(commandType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, commandType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.response.DeviceCommand)) {
      return super.equals(obj);
    }
    ds.response.DeviceCommand other = (ds.response.DeviceCommand) obj;

    if (!getDeviceId()
        .equals(other.getDeviceId())) return false;
    if (getIntensityLevel()
        != other.getIntensityLevel()) return false;
    if (!getCommandType()
        .equals(other.getCommandType())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceId().hashCode();
    hash = (37 * hash) + INTENSITY_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getIntensityLevel();
    hash = (37 * hash) + COMMAND_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getCommandType().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.response.DeviceCommand parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.response.DeviceCommand parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.response.DeviceCommand parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.response.DeviceCommand parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.response.DeviceCommand parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.response.DeviceCommand parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.response.DeviceCommand parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ds.response.DeviceCommand parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ds.response.DeviceCommand parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ds.response.DeviceCommand parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.response.DeviceCommand parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ds.response.DeviceCommand parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.response.DeviceCommand prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code response.DeviceCommand}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:response.DeviceCommand)
      ds.response.DeviceCommandOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.response.ClimateResponseOuterClass.internal_static_response_DeviceCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.response.ClimateResponseOuterClass.internal_static_response_DeviceCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.response.DeviceCommand.class, ds.response.DeviceCommand.Builder.class);
    }

    // Construct using ds.response.DeviceCommand.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      deviceId_ = "";
      intensityLevel_ = 0;
      commandType_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.response.ClimateResponseOuterClass.internal_static_response_DeviceCommand_descriptor;
    }

    @java.lang.Override
    public ds.response.DeviceCommand getDefaultInstanceForType() {
      return ds.response.DeviceCommand.getDefaultInstance();
    }

    @java.lang.Override
    public ds.response.DeviceCommand build() {
      ds.response.DeviceCommand result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.response.DeviceCommand buildPartial() {
      ds.response.DeviceCommand result = new ds.response.DeviceCommand(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ds.response.DeviceCommand result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.deviceId_ = deviceId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.intensityLevel_ = intensityLevel_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.commandType_ = commandType_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.response.DeviceCommand) {
        return mergeFrom((ds.response.DeviceCommand)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.response.DeviceCommand other) {
      if (other == ds.response.DeviceCommand.getDefaultInstance()) return this;
      if (!other.getDeviceId().isEmpty()) {
        deviceId_ = other.deviceId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getIntensityLevel() != 0) {
        setIntensityLevel(other.getIntensityLevel());
      }
      if (!other.getCommandType().isEmpty()) {
        commandType_ = other.commandType_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              deviceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              intensityLevel_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              commandType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object deviceId_ = "";
    /**
     * <code>string device_id = 1;</code>
     * @return The deviceId.
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string device_id = 1;</code>
     * @return The bytes for deviceId.
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string device_id = 1;</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      deviceId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string device_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      deviceId_ = getDefaultInstance().getDeviceId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string device_id = 1;</code>
     * @param value The bytes for deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      deviceId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int intensityLevel_ ;
    /**
     * <code>int32 intensity_level = 2;</code>
     * @return The intensityLevel.
     */
    @java.lang.Override
    public int getIntensityLevel() {
      return intensityLevel_;
    }
    /**
     * <code>int32 intensity_level = 2;</code>
     * @param value The intensityLevel to set.
     * @return This builder for chaining.
     */
    public Builder setIntensityLevel(int value) {

      intensityLevel_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 intensity_level = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIntensityLevel() {
      bitField0_ = (bitField0_ & ~0x00000002);
      intensityLevel_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object commandType_ = "";
    /**
     * <pre>
     * "activate", "deactivate", "adjust"
     * </pre>
     *
     * <code>string command_type = 3;</code>
     * @return The commandType.
     */
    public java.lang.String getCommandType() {
      java.lang.Object ref = commandType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commandType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "activate", "deactivate", "adjust"
     * </pre>
     *
     * <code>string command_type = 3;</code>
     * @return The bytes for commandType.
     */
    public com.google.protobuf.ByteString
        getCommandTypeBytes() {
      java.lang.Object ref = commandType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commandType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "activate", "deactivate", "adjust"
     * </pre>
     *
     * <code>string command_type = 3;</code>
     * @param value The commandType to set.
     * @return This builder for chaining.
     */
    public Builder setCommandType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      commandType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "activate", "deactivate", "adjust"
     * </pre>
     *
     * <code>string command_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommandType() {
      commandType_ = getDefaultInstance().getCommandType();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "activate", "deactivate", "adjust"
     * </pre>
     *
     * <code>string command_type = 3;</code>
     * @param value The bytes for commandType to set.
     * @return This builder for chaining.
     */
    public Builder setCommandTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      commandType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:response.DeviceCommand)
  }

  // @@protoc_insertion_point(class_scope:response.DeviceCommand)
  private static final ds.response.DeviceCommand DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.response.DeviceCommand();
  }

  public static ds.response.DeviceCommand getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeviceCommand>
      PARSER = new com.google.protobuf.AbstractParser<DeviceCommand>() {
    @java.lang.Override
    public DeviceCommand parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DeviceCommand> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeviceCommand> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.response.DeviceCommand getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

